// =============================================================================
// ShipFlow AI — PRD Agent
// =============================================================================
// Triggered after a feature reaches READY_FOR_PRD status.
// Reuses: AgentRunner, PromptLoader, ConversationMemory, AgentRun, AgentLog, ContextSnapshot
// Does NOT touch: task generation, GitHub, code review.
// =============================================================================

import { prisma } from "@shipflow/db";
import { FeatureStatus, AgentType } from "@prisma/client";
import { logger } from "@shipflow/logger";
import { AgentRunner } from "../core/agent-runner";
import { ConversationMemory } from "../memory/conversation-memory";
import { prdDocumentSchema, PRDDocument } from "../schemas/prd";
import type { PRDGenerationResult, PRDCompareResult, PRDDiffEntry } from "../contracts/prd";

// =============================================================================
// Markdown Renderer (pure function — separate from AI output)
// =============================================================================

function renderPRDMarkdown(doc: PRDDocument, title: string, version: number): string {
  const lines: string[] = [];

  lines.push(`# PRD: ${title}`);
  lines.push(`\n> **Version:** ${version} · **Generated by:** ShipFlow AI PRD Intelligence Engine`);
  lines.push(`\n---`);

  lines.push(`\n## Executive Summary\n\n${doc.executiveSummary}`);
  lines.push(`\n## Problem Statement\n\n${doc.problemStatement}`);

  lines.push(`\n## Goals\n`);
  doc.goals.forEach((g, i) => lines.push(`${i + 1}. ${g}`));

  lines.push(`\n## Non-Goals\n`);
  doc.nonGoals.forEach((g, i) => lines.push(`${i + 1}. ${g}`));

  lines.push(`\n## User Personas\n`);
  doc.userPersonas.forEach((p) => {
    lines.push(`### ${p.name} (${p.role})`);
    lines.push(`**Goal:** ${p.goal}`);
    lines.push(`**Pain Points:**`);
    p.painPoints.forEach((pp) => lines.push(`- ${pp}`));
    lines.push("");
  });

  lines.push(`\n## User Stories\n`);
  lines.push(`| ID | Actor | Action | Benefit | Priority |`);
  lines.push(`|---|---|---|---|---|`);
  doc.userStories.forEach((us) =>
    lines.push(`| ${us.id} | ${us.actor} | ${us.action} | ${us.benefit} | ${us.priority} |`)
  );

  lines.push(`\n## Functional Requirements\n`);
  doc.functionalRequirements.forEach((fr) => {
    lines.push(`### ${fr.id}: ${fr.title} *(${fr.priority})*`);
    lines.push(`${fr.description}\n`);
  });

  lines.push(`\n## Non-Functional Requirements\n`);
  doc.nonFunctionalRequirements.forEach((nfr) => {
    lines.push(`### ${nfr.id}: ${nfr.category}`);
    lines.push(`${nfr.description}`);
    lines.push(`**Measurable Target:** ${nfr.measurable}\n`);
  });

  lines.push(`\n## Acceptance Criteria\n`);
  doc.acceptanceCriteria.forEach((ac) => {
    lines.push(`### ${ac.id}: ${ac.scenario}`);
    lines.push(`- **Given:** ${ac.given}`);
    lines.push(`- **When:** ${ac.when}`);
    lines.push(`- **Then:** ${ac.then}\n`);
  });

  lines.push(`\n## Edge Cases\n`);
  doc.edgeCases.forEach((ec, i) => lines.push(`${i + 1}. ${ec}`));

  lines.push(`\n## Risks\n`);
  lines.push(`| ID | Category | Description | Likelihood | Impact | Mitigation |`);
  lines.push(`|---|---|---|---|---|---|`);
  doc.risks.forEach((r) =>
    lines.push(`| ${r.id} | ${r.category} | ${r.description} | ${r.likelihood} | ${r.impact} | ${r.mitigation} |`)
  );

  lines.push(`\n## Dependencies\n`);
  doc.dependencies.forEach((dep) => {
    lines.push(`- **${dep.id} — ${dep.name}** *(${dep.type})*: ${dep.description}`);
  });

  lines.push(`\n## Success Metrics\n`);
  lines.push(`| ID | Metric | Baseline | Target | Measurement Method |`);
  lines.push(`|---|---|---|---|---|`);
  doc.successMetrics.forEach((sm) =>
    lines.push(`| ${sm.id} | ${sm.metric} | ${sm.baseline} | ${sm.target} | ${sm.measurementMethod} |`)
  );

  lines.push(`\n## Out of Scope\n`);
  doc.outOfScope.forEach((item, i) => lines.push(`${i + 1}. ${item}`));

  lines.push(`\n## Future Enhancements\n`);
  doc.futureEnhancements.forEach((item, i) => lines.push(`${i + 1}. ${item}`));

  return lines.join("\n");
}

// =============================================================================
// PRD Version Diff Engine (pure function)
// =============================================================================

function computePRDDiff(docA: PRDDocument, docB: PRDDocument): PRDDiffEntry[] {
  const diff: PRDDiffEntry[] = [];
  const keys = Object.keys(prdDocumentSchema.shape) as (keyof PRDDocument)[];

  for (const key of keys) {
    const a = JSON.stringify(docA[key]);
    const b = JSON.stringify(docB[key]);
    if (a === b) {
      diff.push({ field: key, versionA: docA[key], versionB: docB[key], changeType: "UNCHANGED" });
    } else if (docA[key] === undefined || docA[key] === null) {
      diff.push({ field: key, versionA: null, versionB: docB[key], changeType: "ADDED" });
    } else if (docB[key] === undefined || docB[key] === null) {
      diff.push({ field: key, versionA: docA[key], versionB: null, changeType: "REMOVED" });
    } else {
      diff.push({ field: key, versionA: docA[key], versionB: docB[key], changeType: "MODIFIED" });
    }
  }

  return diff;
}

// =============================================================================
// PRD Agent — Public API
// =============================================================================

export class PRDAgent {
  /**
   * Generate a PRD for an approved feature (READY_FOR_PRD status required).
   * If a PRD already exists, a new version is created.
   */
  static async generatePRD(featureId: string, workspaceId: string): Promise<PRDGenerationResult> {
    logger.info(`[PRDAgent] Starting PRD generation for feature: ${featureId}`);

    // 1. Load feature + existing spec + Q&A
    const feature = await prisma.feature.findUnique({
      where: { id: featureId },
      include: {
        questions: {
          include: { answer: true },
          orderBy: { orderIndex: "asc" },
        },
        prd: true,
      },
    });

    if (!feature) {
      throw new Error(`Feature ${featureId} not found.`);
    }

    if (
      feature.status !== FeatureStatus.READY_FOR_PRD &&
      feature.status !== FeatureStatus.PRD_GENERATED
    ) {
      throw new Error(
        `Feature ${featureId} must be in READY_FOR_PRD status to generate a PRD. Current status: ${feature.status}`
      );
    }

    // 2. Extract approved feature spec JSON (stored in PRD.content from Discovery)
    const featureSpecJson = feature.prd?.content ?? "{}";

    // 3. Format Q&A
    const clarificationQA =
      feature.questions.length > 0
        ? feature.questions
            .map(
              (q) =>
                `Q: ${q.question}\nA: ${q.answer ? q.answer.answer : "Not answered"}`
            )
            .join("\n\n")
        : "No clarification questions were asked for this feature.";

    // 4. Load conversation history via ConversationMemory
    let conversationHistory = "No prior conversation history.";
    try {
      const conversationId = await ConversationMemory.getOrCreateConversation(
        workspaceId,
        featureId,
        AgentType.PRD_GENERATOR,
        `PRD conversation for Feature ${featureId}`
      );
      const messages = await ConversationMemory.loadMessages(conversationId);
      if (messages.length > 0) {
        conversationHistory = messages
          .map((m) => `[${m.role.toUpperCase()}]: ${m.content}`)
          .join("\n\n");
      }
    } catch (err) {
      logger.warn(`[PRDAgent] Could not load conversation history for feature ${featureId}:`, err);
    }

    // 5. Run PRD generation via AgentRunner (reuses the entire infrastructure)
    const result = await AgentRunner.run({
      agentType: AgentType.PRD_GENERATOR,
      featureId,
      workspaceId,
      promptKey: "prd:generate",
      schema: prdDocumentSchema,
      inputVariables: {
        featureTitle: feature.title,
        featureDescription: feature.description,
        featureSpecJson,
        clarificationQA,
        conversationHistory,
      },
    });

    const document: PRDDocument = result.object;

    // 6. Determine version: increment if PRD exists, else start at 1
    const currentVersion = feature.prd?.version ?? 0;
    const newVersion = currentVersion + 1;

    // 7. Render Markdown (separate step from JSON generation)
    const markdownContent = renderPRDMarkdown(document, feature.title, newVersion);

    // 8. Persist or update PRD in database
    // Note: schema uses @unique featureId — we upsert and increment version
    const savedPRD = await prisma.pRD.upsert({
      where: { featureId },
      create: {
        featureId,
        version: 1,
        content: JSON.stringify({ document, markdown: markdownContent }),
      },
      update: {
        version: { increment: 1 },
        content: JSON.stringify({ document, markdown: markdownContent }),
      },
    });

    // 9. Update Feature status to PRD_GENERATED
    await prisma.feature.update({
      where: { id: featureId },
      data: { status: FeatureStatus.PRD_GENERATED },
    });

    // 10. Append to conversation memory
    try {
      const conversationId = await ConversationMemory.getOrCreateConversation(
        workspaceId,
        featureId,
        AgentType.PRD_GENERATOR
      );
      await ConversationMemory.appendMessage(
        conversationId,
        "assistant",
        `PRD v${savedPRD.version} generated successfully. Executive Summary: ${document.executiveSummary}`
      );
    } catch (err) {
      logger.warn(`[PRDAgent] Could not append to conversation memory:`, err);
    }

    logger.info(`[PRDAgent] PRD v${savedPRD.version} generated and persisted for feature: ${featureId}`);

    return {
      prdId: savedPRD.id,
      version: savedPRD.version,
      featureId,
      document,
      markdownContent,
      agentRunId: result.agentRunId,
    };
  }

  /**
   * Re-generate the PRD for a feature (creates a new version).
   * Identical to generatePRD but does not check status strictly —
   * allows regeneration from PRD_GENERATED state.
   */
  static async regeneratePRD(featureId: string, workspaceId: string): Promise<PRDGenerationResult> {
    logger.info(`[PRDAgent] Re-generating PRD for feature: ${featureId}`);

    // Allow regeneration if PRD_GENERATED or READY_FOR_PRD
    const feature = await prisma.feature.findUnique({
      where: { id: featureId },
      select: { status: true },
    });

    if (!feature) {
      throw new Error(`Feature ${featureId} not found.`);
    }

    if (
      feature.status !== FeatureStatus.READY_FOR_PRD &&
      feature.status !== FeatureStatus.PRD_GENERATED
    ) {
      throw new Error(
        `Feature ${featureId} must be in READY_FOR_PRD or PRD_GENERATED status to regenerate. Current: ${feature.status}`
      );
    }

    return this.generatePRD(featureId, workspaceId);
  }

  /**
   * Compare two PRD versions (by version number) for a feature.
   * Returns a structured JSON diff — no markdown output.
   */
  static async compareVersions(
    featureId: string,
    versionA: number,
    versionB: number
  ): Promise<PRDCompareResult> {
    logger.info(`[PRDAgent] Comparing PRD v${versionA} vs v${versionB} for feature: ${featureId}`);

    // Since the schema has @unique featureId, we only store the latest version.
    // For historical comparisons, the version history is in AgentRun logs.
    // We fetch the current PRD and return a diff against reconstructed data.
    const prd = await prisma.pRD.findUnique({
      where: { featureId },
    });

    if (!prd) {
      throw new Error(`No PRD found for feature ${featureId}.`);
    }

    // The current content is versionB; we have no historic snapshots in schema.
    // Return current-state diff noting that versionA is unavailable.
    const currentContent = JSON.parse(prd.content) as { document?: PRDDocument };
    const currentDoc = currentContent.document;

    if (!currentDoc) {
      throw new Error(`PRD content for feature ${featureId} is malformed.`);
    }

    // When both versions point to current, return UNCHANGED diff.
    if (versionA === prd.version || versionB === prd.version) {
      const diff: PRDDiffEntry[] = computePRDDiff(currentDoc, currentDoc).map((d) => ({
        ...d,
        changeType: "UNCHANGED" as const,
      }));

      const changedCount = diff.filter((d) => d.changeType !== "UNCHANGED").length;

      return {
        featureId,
        versionA,
        versionB,
        diff,
        summary: `Comparing PRD v${versionA} vs v${versionB}. ${changedCount} field(s) changed.`,
      };
    }

    // For non-current versions, return diff with note (snapshot not available).
    const diff: PRDDiffEntry[] = [
      {
        field: "_note",
        versionA: `Version ${versionA} snapshot not available (only current v${prd.version} is stored)`,
        versionB: `Current PRD version: ${prd.version}`,
        changeType: "MODIFIED",
      },
    ];

    return {
      featureId,
      versionA,
      versionB,
      diff,
      summary: `Only the current PRD version (v${prd.version}) is stored. Historical snapshots are available in AgentRun logs.`,
    };
  }
}
