// =============================================================================
// ShipFlow AI — Planning Agent Output Schemas
// =============================================================================

import { z } from "zod";

/**
 * Task reasoning structure.
 */
export const taskReasoningSchema = z.object({
  whyThisTaskExists: z.string(),
  whyThisOrder: z.string(),
  whyThisDependsOn: z.string(),
});

/**
 * A single engineering task with rich planning metadata.
 * Note: filesAffected contains strictly actual repository file paths.
 * All other metadata is stored in ContextSnapshot.
 */
export const engineeringTaskSchema = z.object({
  id: z.string(), // e.g., "TASK-001"
  title: z.string(),
  description: z.string(),
  filesAffected: z.array(z.string()), // STRICTLY actual repo file paths (e.g. apps/web/src/...)
  epicId: z.string(),
  storyPoints: z.number().int().min(1),
  complexity: z.enum(["LOW", "MEDIUM", "HIGH"]),
  estimatedHours: z.number().int().min(1),
  labels: z.array(z.string()),
  blockers: z.array(z.string()), // Dependency task IDs
  acceptanceCriteria: z.array(z.string()),
  confidence: z.object({
    score: z.number().min(0).max(100),
    reason: z.string(),
  }),
  riskAnalysis: z.object({
    level: z.enum(["LOW", "MEDIUM", "HIGH"]),
    description: z.string(),
    mitigation: z.string(),
  }),
  affectedAreas: z.array(z.enum([
    "Frontend",
    "Backend",
    "Database",
    "API",
    "Infrastructure",
    "Documentation",
    "Testing"
  ])),
  reasoning: taskReasoningSchema,
});

/**
 * A single high-level epic grouping engineering tasks.
 */
export const engineeringEpicSchema = z.object({
  id: z.string(), // e.g., "EPIC-001"
  title: z.string(),
  description: z.string(),
  riskAnalysis: z.object({
    level: z.enum(["LOW", "MEDIUM", "HIGH"]),
    description: z.string(),
    mitigation: z.string(),
  }),
});

/**
 * Structured testing strategy breakdown.
 */
export const testingStrategySchema = z.object({
  unit: z.string(),
  integration: z.string(),
  endToEnd: z.string(),
  performance: z.string(),
  security: z.string(),
});

/**
 * Top-level execution waves, critical path, and parallel work groups.
 */
export const executionMetadataSchema = z.object({
  criticalPath: z.array(z.string()), // ordered list of task IDs
  parallelWorkGroups: z.array(z.array(z.string())), // groups of tasks that can run in parallel
});

/**
 * Recommended commit sequence and phases.
 */
export const implementationStrategySchema = z.object({
  recommendedCommitSequence: z.array(z.string()),
  implementationPhases: z.array(z.object({
    name: z.string(),
    description: z.string(),
    taskIds: z.array(z.string()),
  })),
});

/**
 * Sprint or milestone grouping of tasks.
 */
export const milestoneSchema = z.object({
  id: z.string(), // e.g. "MILESTONE-1"
  title: z.string(),
  description: z.string(),
  taskIds: z.array(z.string()),
});

/**
 * Overall planning metrics computed or generated by the agent.
 */
export const planningMetricsSchema = z.object({
  totalTasks: z.number().int().min(0),
  totalStoryPoints: z.number().int().min(0),
  estimatedHours: z.number().int().min(0),
  criticalPathLength: z.number().int().min(0),
  parallelizationPercentage: z.number().min(0).max(100),
  averageConfidence: z.number().min(0).max(100),
  riskScore: z.number().min(0).max(100), // general risk index
  testingCoverage: z.number().min(0).max(100), // target testing coverage estimate
});

/**
 * Complete structured engineering plan output schema.
 */
export const engineeringPlanSchema = z.object({
  epics: z.array(engineeringEpicSchema),
  tasks: z.array(engineeringTaskSchema),
  testingStrategy: testingStrategySchema,
  executionMetadata: executionMetadataSchema,
  implementationStrategy: implementationStrategySchema,
  milestones: z.array(milestoneSchema),
  metrics: planningMetricsSchema,
});

export type EngineeringPlan = z.infer<typeof engineeringPlanSchema>;
export type EngineeringEpic = z.infer<typeof engineeringEpicSchema>;
export type EngineeringTask = z.infer<typeof engineeringTaskSchema>;
export type TestingStrategy = z.infer<typeof testingStrategySchema>;
export type ExecutionMetadata = z.infer<typeof executionMetadataSchema>;
export type ImplementationStrategy = z.infer<typeof implementationStrategySchema>;
export type Milestone = z.infer<typeof milestoneSchema>;
export type PlanningMetrics = z.infer<typeof planningMetricsSchema>;
